language: generic
addons:
  apt:
    packages:
    - cmake
    - libboost-all-dev
    - libgoogle-glog-dev
    - wget
    - g++-5
    sources:
    - ubuntu-toolchain-r-test
matrix:
  include:
  #- os: osx
    #compiler: clang
    #env: ITK_VERSION=v4.12.1
  - os: linux
    compiler: gcc
    env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5 ITK_VERSION=v4.12.1
cache:
- directories:
  - $HOME/itk-v4.12.1-build
  - $HOME/itk-v4.12.1
before_script:
- g++ --version
- export NUM_THREADS=4
- export GLOG_SOURCE_DIR=$HOME/glog
- export GLOG_BUILD_DIR=$HOME/glog-build
- cd $HOME
- git clone --branch v035 https://github.com/google/glog.git
- mkdir ${GLOG_BUILD_DIR}
- cd ${GLOG_BUILD_DIR}
- cmake ${GLOG_SOURCE_DIR} -DCMAKE_BUILD_TYPE=Release
- make --jobs=$NUM_THREADS --keep-going
- cd $HOME
- export ITK_SOURCE_DIR=$HOME/itk-${ITK_VERSION}
- export ITK_BUILD_DIR=${ITK_SOURCE_DIR}-build
- if ! test -e ${ITK_SOURCE_DIR}; then git clone --branch ${ITK_VERSION} git://itk.org/ITK.git ${ITK_SOURCE_DIR}; fi
- ls ${ITK_SOURCE_DIR}
- if ! test -e ${ITK_BUILD_DIR}; then mkdir ${ITK_BUILD_DIR}; fi
- cd ${ITK_BUILD_DIR}
- cmake ${ITK_SOURCE_DIR} -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF
  -DBUILD_TESTING=OFF -DModule_ITKReview=ON
- make --jobs=$NUM_THREADS --keep-going
- cd /home/travis/build/UCL/petmr-rd-tools
- cmake . -DCMAKE_BUILD_TYPE=Release -DITK_DIR=${ITK_BUILD_DIR} -Dglog_DIR=${GLOG_BUILD_DIR}
script: cmake --build .
