language: cpp
addons:
  apt:
    packages:
    - cmake
    - libgdcm2-dev
    - libboost-all-dev
    - libgoogle-glog-dev
    sources:
    - kalakris-cmake
matrix:
  include:
  - os: osx
    compiler: clang
    env: ITK_VERSION=v4.12.1
  - os: linux
    compiler: gcc
    env: ITK_VERSION=v4.12.1
cache:
- directories:
  - $HOME/itk-v4.12.1-build
  - $HOME/itk-v4.12.1
before_script:
- export NUM_THREADS=4
- export ITK_SOURCE_DIR=$HOME/itk-${ITK_VERSION}
- export ITK_BUILD_DIR=${ITK_SOURCE_DIR}-build
- if ! test -e ${ITK_SOURCE_DIR}/CMakeLists.txt; then rm -fr $ITK_SOURCE_DIR; fi
- if ! test -d ${ITK_SOURCE_DIR}; then git clone --branch ${ITK_VERSION} git://itk.org/ITK.git
  ${ITK_SOURCE_DIR}; fi
- if ! test -d ${ITK_BUILD_DIR}; then mkdir ${ITK_BUILD_DIR}; fi
- cd ${ITK_BUILD_DIR}
- cmake ${ITK_SOURCE_DIR} -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF
  -DBUILD_TESTING=OFF -DITK_USE_SYSTEM_GDCM=ON -DModule_ITKReview=ON
- make --jobs=$NUM_THREADS --keep-going
- cd -
- cd ..
- mkdir build
- cd build
- cmake ../petmr-rd-tools -DCMAKE_BUILD_TYPE=Release
script: cmake --build
