language: cpp
addons:
  apt:
    packages:
    - cmake
    - libboost-all-dev
    - libgoogle-glog-dev
    - wget
    sources:
    - kalakris-cmake
matrix:
  include:
  - os: osx
    compiler: clang
    env: ITK_VERSION=v4.12.1
  - os: linux
    compiler: gcc
    env: ITK_VERSION=v4.12.1
cache:
- directories:
  - $HOME/itk-v4.12.1-build
  - $HOME/itk-v4.12.1
  - $HOME/gdcm-2.8.4-build
  - $HOME/gdcm-2.8.4
before_script:
- export NUM_THREADS=4
- export GDCM_SOURCE_DIR=$HOME/gdcm-2.8.4
- wget https://downloads.sourceforge.net/project/gdcm/gdcm%202.x/GDCM%202.8.4/gdcm-2.8.4.tar.gz
- tar xvzf gdcm-2.8.4.tar.gz
- pwd
- ls *
- export GDCM_BUILD_DIR=$HOME/gdcm-2.8.4-build
- cd ${GDCM_BUILD_DIR}
- cmake ${GDCM_SOURCE_DIR} -DCMAKE_BUILD_TYPE=Release -DGDCM_BUILD_SHARED_LIBS=ON
- make --jobs=$NUM_THREADS --keep-going && make install
- export ITK_SOURCE_DIR=$HOME/itk-${ITK_VERSION}
- export ITK_BUILD_DIR=${ITK_SOURCE_DIR}-build
- if ! test -e ${ITK_SOURCE_DIR}/CMakeLists.txt; then rm -fr $ITK_SOURCE_DIR; fi
- if ! test -d ${ITK_SOURCE_DIR}; then git clone --branch ${ITK_VERSION} git://itk.org/ITK.git
  ${ITK_SOURCE_DIR}; fi
- if ! test -d ${ITK_BUILD_DIR}; then mkdir ${ITK_BUILD_DIR}; fi
- cd ${ITK_BUILD_DIR}
- cmake ${ITK_SOURCE_DIR} -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF
  -DBUILD_TESTING=OFF -DITK_USE_SYSTEM_GDCM=ON -DModule_ITKReview=ON
- make --jobs=$NUM_THREADS --keep-going
- cd -
- cd ..
- mkdir build
- cd build
- cmake ../petmr-rd-tools -DCMAKE_BUILD_TYPE=Release
script: cmake --build
