language: cpp
addons:
  apt:
    packages:
    - cmake
    - libgdcm2-dev
    - libboost-all-dev
    - libinsighttoolkit4-dev
    sources:
    - kalakris-cmake
matrix:
  include:
  - os: osx
    compiler: clang
    env: ITK_VERSION=v4.12.1
  - os: linux
    compiler: gcc
    env: ITK_VERSION=v4.12.1
before_script:
- export NUM_THREADS=4
- cmake ../petmr-rd-tools -DCMAKE_BUILD_TYPE=Release
script: cmake --build
