# version format
version: "{build}"

image: Visual Studio 2013
platform: x64
configuration: release

clone_folder: C:\projects\petmr-rd-tools

environment:
  ITKSRC: C:\projects\deps\ITK
  ITKINSTALL: C:\projects\deps\ITK-4.12.2
  ITKBUILD: C:\projects\deps\ITK-BUILD
  GLOGINSTALL: C:\projects\deps\glog-INSTALL
  GLOGBUILD: C:\projects\deps\glog-BUILD
  BOOSTSRC: C:\projects\deps\boost_1_63_0
  BOOSTINSTALL: C:\projects\deps\boost-INSTALL

install:
  - IF NOT EXIST C:\projects\deps mkdir C:\projects\deps
  - cd C:\projects\deps
  - dir C:\Libraries\boost_1_63_0
  - set ITK_URL="https://github.com/InsightSoftwareConsortium/ITK.git"
  - IF NOT EXIST %ITKINSTALL% ( 
      git clone -b v4.12.2 %ITK_URL% &&
      mkdir %ITKBUILD% &&
      cd %ITKBUILD% &&
      cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=%ITKINSTALL% -DModule_ITKReview=ON ..\ITK &&
      msbuild INSTALL.vcxproj
    )
  - cd C:\projects\deps
  - set BOOST_URL="https://dl.bintray.com/boostorg/release/1.63.0/binaries/boost_1_63_0-msvc-12.0-64.exe"
  - IF NOT EXIST C:\projects\deps\boost_1_63_0-msvc-12.0-64.exe appveyor DownloadFile %BOOST_URL%
  - IF NOT EXIST %BOOSTINSTALL% ( 
      boost_1_63_0-msvc-12.0-64.exe
    )
  - dir %BOOSTINSTALL%

cache:
  - C:\projects\deps\ITK-4.12.2
  - C:\projects\deps\boost-INSTALL

build_script:
  - cd C:\projects\petmr-rd-tools
  - dir C:\Libraries\boost_1_63_0
