# version format
version: "{build}"

image: Visual Studio 2017
platform: x64
configuration: release

clone_folder: C:\projects\petmr-rd-tools

environment:
  ITKSRC: C:\projects\deps\ITK
  ITKINSTALL: C:\projects\deps\ITK-4.12.2
  ITKBUILD: C:\projects\deps\ITK-BUILD
  GLOGINSTALL: C:\projects\deps\glog-INSTALL
  GLOGBUILD: C:\projects\deps\glog-BUILD
  BOOSTSRC: C:\projects\deps\boost_1_63_0
  BOOSTINSTALL: C:\projects\deps\boost-INSTALL

install:
  - nuget install boost -OutputDirectory C:\projects\petmr-rd-tools\boost
  - nuget install itk_static_vc141-x64-release C:\projects\petmr-rd-tools\ITK
  - nuget install glog C:\projects\petmr-rd-tools\glog
  - IF NOT EXIST C:\projects\deps mkdir C:\projects\deps
  - cd C:\projects\deps

cache:
  - C:\projects\deps\glog-INSTALL -> appveyor.yml
  - C:\projects\deps\ITK-4.12.2 -> appveyor.yml
  - C:\projects\deps\boost_1_63_0.zip -> appveyor.yml
  - C:\projects\deps\boost_1_63_0 -> appveyor.yml
  - C:\projects\deps\boost-INSTALL -> appveyor.yml

build_script:
  - cd C:\projects\petmr-rd-tools
  - dir boost.1.65.1.0
  - dir itk_static_vc141-x64-release.4.12.2
  - dir glog.0.3.3.0
  - cmake
    -DCMAKE_BUILD_TYPE=Release
    -DBOOST_ROOT=.\boost
    -DITK_DIR=.\ITK
    -DGLOG_DIR=.\glog
    -DCMAKE_INSTALL_PATH=. .
  - msbuild INSTALL.vcxproj
