# version format
version: "{build}"

image: Visual Studio 2013
platform: Any CPU
configuration: release

clone_folder: C:\projects\petmr-rd-tools

environment:
  ITKSRC: C:\projects\deps\ITK
  ITKINSTALL: C:\projects\deps\ITK-4.12.2
  ITKBUILD: C:\projects\deps\ITK-BUILD
  GLOGINSTALL: C:\projects\deps\glog-INSTALL
  GLOGBUILD: C:\projects\deps\glog-BUILD
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_INCLUDEDIR: C:\Libraries\boost_1_59_0\boost
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-12.0

install:
  - IF NOT EXIST C:\projects\deps mkdir C:\projects\deps
  - cd C:\projects\deps
  - set GLOG_URL="https://github.com/google/glog"
  - git clone -b v035 %GLOG_URL%
  - IF NOT EXIST %GLOGINSTALL% (
      mkdir %GLOGBUILD% &&
      cd %GLOGBUILD% &&
      cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%GLOGINSTALL% ..\glog &&
      msbuild INSTALL.vcxproj
    )
  - cd C:\projects\deps
  - set ITK_URL="https://github.com/InsightSoftwareConsortium/ITK.git"
  - git clone -b v4.12.2 %ITK_URL%
  - IF NOT EXIST %ITKINSTALL% ( 
      mkdir %ITKBUILD% &&
      cd %ITKBUILD% &&
      cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=%ITKINSTALL% -DModule_ITKReview=ON ..\ITK &&
      msbuild INSTALL.vcxproj
    )

cache:
  - C:\projects\deps\glog-INSTALL -> appveyor.yml
  - C:\projects\deps\ITK-4.12.2 -> appveyor.yml

build_script:
  - cd C:\projects\petmr-rd-tools
  - cmake 
    -DCMAKE_BUILD_TYPE=Release 
    -DGLOG_DIR="%GLOGINSTALL%" 
    -DCMAKE_PREFIX_PATH=%ITKINSTALL%
    -DBoost_DEBUG=ON
    -DBOOST_ROOT="%BOOST_ROOT%"
    -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%"
    -DBOOST_INCLUDEDIR="%BOOST_INCLUDEDIR%"
    -DCMAKE_INSTALL_PATH=. .
  - msbuild INSTALL.vcxproj
