# version format
version: "{build}"

image: Visual Studio 2017
platform: x64
configuration: release

clone_folder: C:\projects\petmr-rd-tools

environment:
  ITKSRC: C:\projects\deps\ITK
  ITKINSTALL: C:\projects\deps\ITK-4.12.2
  ITKBUILD: C:\projects\deps\ITK-BUILD
  GLOGINSTALL: C:\projects\deps\glog-INSTALL
  GLOGBUILD: C:\projects\deps\glog-BUILD
  BOOSTSRC: C:\projects\deps\boost_1_63_0
  BOOSTINSTALL: C:\projects\deps\boost-INSTALL

install:
  - nuget install glog -OutputDirectory C:\projects\petmr-rd-tools\glog -Version 0.3.3
  - IF NOT EXIST C:\projects\deps mkdir C:\projects\deps
  - cd C:\projects\deps
  - set ITK_URL="https://github.com/InsightSoftwareConsortium/ITK.git"
  - IF NOT EXIST %ITKINSTALL% ( 
      git clone -b v4.12.2 %ITK_URL% &&
      mkdir %ITKBUILD% &&
      cd %ITKBUILD% &&
      cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DModule_ITKReview=ON ..\ITK &&
      msbuild INSTALL.vcxproj
    )

cache:
  - C:\projects\deps\glog-INSTALL -> appveyor.yml
  - C:\projects\deps\ITK-4.12.2 -> appveyor.yml

build_script:
  - cd C:\projects\petmr-rd-tools
  - dir C:\Libraries\boost_1_65_1
  - dir C:\projects\petmr-rd-tools\glog\glog.0.3.3.0\build\native\include
  - cmake
    -DCMAKE_BUILD_TYPE=Release
    -DBOOST_ROOT=C:\Libraries\boost_1_65_1
    -DGLOG_DIR=C:\projects\petmr-rd-tools\glog\glog.0.3.3.0\build\native
    -DCMAKE_INSTALL_PATH=. .
  - msbuild INSTALL.vcxproj
