# version format
version: "{build}"

image: Visual Studio 2015
platform: x64
configuration: release

clone_folder: C:\projects\petmr-rd-tools

environment:
  ITKSRC: C:\projects\deps\ITK
  ITKINSTALL: C:\projects\deps\ITK-4.12.2
  ITKBUILD: C:\projects\deps\ITK-BUILD
  GLOGINSTALL: C:\projects\deps\glog-INSTALL
  GLOGBUILD: C:\projects\deps\glog-BUILD
  BOOSTSRC: C:\projects\deps\boost_1_63_0
  BOOSTINSTALL: C:\projects\deps\boost-INSTALL

install:
  - IF NOT EXIST C:\projects\deps mkdir C:\projects\deps
  - cd C:\projects\deps
  - set BOOST_URL="http://downloads.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.zip"
  - IF NOT EXIST C:\projects\deps\boost_1_63_0.zip appveyor DownloadFile %BOOST_URL% -FileName boost_1_63_0.zip
  - IF NOT EXIST %BOOSTINSTALL% ( 7z x boost_1_63_0.zip -oC:\projects\deps > nul &&
      cd %BOOSTSRC% &&
      bootstrap.bat --with-libraries=system,filesystem,thread,program_options,chrono,date_time,regex &&
      b2.exe install --prefix=%BOOSTINSTALL%
    )
  - ls %BOOSTINSTALL%
  - cd C:\projects\deps
  - set GLOG_URL="https://github.com/google/glog"
  - git clone -b v035 %GLOG_URL%
  - IF NOT EXIST %GLOGINSTALL% (
      mkdir %GLOGBUILD% &&
      cd %GLOGBUILD% &&
      cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="C:\Program Files (x86)\glog" ..\glog &&
      msbuild INSTALL.vcxproj
    )
  - cd C:\projects\deps
  - set ITK_URL="https://github.com/InsightSoftwareConsortium/ITK.git"
  - IF NOT EXIST %ITKINSTALL% ( 
      git clone -b v4.12.2 %ITK_URL% &&
      mkdir %ITKBUILD% &&
      cd %ITKBUILD% &&
      cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=%ITKINSTALL% -DModule_ITKReview=ON ..\ITK &&
      msbuild INSTALL.vcxproj
    )

cache:
  - C:\projects\deps\glog-INSTALL -> appveyor.yml
  - C:\projects\deps\ITK-4.12.2 -> appveyor.yml
  - C:\projects\deps\boost_1_63_0.zip -> appveyor.yml
  - C:\projects\deps\boost_1_63_0 -> appveyor.yml
  - C:\projects\deps\boost-INSTALL -> appveyor.yml

build_script:
  - cd C:\projects\petmr-rd-tools
  - cmake
    -DCMAKE_BUILD_TYPE=Release
    -DBoost_USE_STATIC_LIBS:BOOL=ON
    -DCMAKE_PREFIX_PATH:STRING="%ITKINSTALL%;%BOOSTINSTALL%;C:/Program Files (x86)/glog/lib/cmake/glog"
    -DBOOST_ROOT="%BOOSTINSTALL%"
    -DBOOST_LIBRARYDIR="%BOOSTINSTALL%\lib"
    -DBoost_DEBUG=ON
    -DCMAKE_INSTALL_PATH=. .
  - msbuild INSTALL.vcxproj
