# version format
version: "{build}"

image: Visual Studio 2017
platform: x64
configuration: release

clone_folder: C:\projects\petmr-rd-tools

environment:
  ITKSRC: C:\projects\deps\ITK
  ITKINSTALL: C:\projects\deps\ITK-4.12.2
  ITKBUILD: C:\projects\deps\ITK-BUILD
  GLOGINSTALL: C:\projects\deps\glog-INSTALL
  GLOGBUILD: C:\projects\deps\glog-BUILD
  BOOSTSRC: C:\projects\deps\boost_1_63_0
  BOOSTINSTALL: C:\projects\deps\boost-INSTALL

install:
  - nuget install boost -OutputDirectory C:\projects\petmr-rd-tools\boost -Version 1.65.1
  - nuget install itk_static_vc141-x64-release -OutputDirectory C:\projects\petmr-rd-tools\ITK -Version 4.12.2
  - nuget install glog -OutputDirectory C:\projects\petmr-rd-tools\glog -Version 0.3.3
  - IF NOT EXIST C:\projects\deps mkdir C:\projects\deps
  - cd C:\projects\deps

cache:
  - C:\projects\deps\glog-INSTALL -> appveyor.yml
  - C:\projects\deps\ITK-4.12.2 -> appveyor.yml
  - C:\projects\deps\boost_1_63_0.zip -> appveyor.yml
  - C:\projects\deps\boost_1_63_0 -> appveyor.yml
  - C:\projects\deps\boost-INSTALL -> appveyor.yml

build_script:
  - cd C:\projects\petmr-rd-tools
  - dir C:\projects\petmr-rd-tools\boost\boost.1.65.1.0\build
  - dir C:\projects\petmr-rd-tools\ITK\itk_static_vc141-x64-release.4.12.2\build\native\bin
  - dir C:\projects\petmr-rd-tools\glog\glog.0.3.3.0\build\native\include
  - cmake
    -DCMAKE_BUILD_TYPE=Release
    -DBOOST_ROOT=C:\projects\petmr-rd-tools\boost\boost.1.65.1.0\build\native
    -DITK_DIR=C:\projects\petmr-rd-tools\ITK\itk_static_vc141-x64-release.4.12.2\build\native
    -DGLOG_DIR=C:\projects\petmr-rd-tools\glog\glog.0.3.3.0\build\native
    -DCMAKE_INSTALL_PATH=. .
  - msbuild INSTALL.vcxproj
